import {
  curveBasis,
  curveBasisOpen,
  curveBasisClosed,
  curveBumpX,
  curveBumpY,
  curveBundle,
  curveCardinal,
  curveCardinalOpen,
  curveCardinalClosed,
  curveCatmullRom,
  curveCatmullRomOpen,
  curveCatmullRomClosed,
  curveLinear,
  curveLinearClosed,
  curveMonotoneX,
  curveMonotoneY,
  curveNatural,
  curveStep,
  curveStepAfter,
  curveStepBefore,
} from 'd3-shape'

export const CurveMode = {
  'basis': curveBasis,
  'basis-open': curveBasisOpen,
  'basis-closed': curveBasisClosed,
  'bump-x': curveBumpX,
  'bump-y': curveBumpY,
  'bundle': curveBundle,
  'cardinal': curveCardinal,
  'cardinal-open': curveCardinalOpen,
  'cardinal-closed': curveCardinalClosed,
  'catmull-rom': curveCatmullRom,
  'catmull-rom-open': curveCatmullRomOpen,
  'catmull-rom-closed': curveCatmullRomClosed,
  'linear': curveLinear,
  'linear-closed': curveLinearClosed,
  'monotone-x': curveMonotoneX,
  'monotone-y': curveMonotoneY,
  'natural': curveNatural,
  'step': curveStep,
  'step-after': curveStepAfter,
  'step-before': curveStepBefore,
}

export type CurveModes = 'basis' | 'basis-open' | 'basis-closed' | 'bump-x' | 'bump-y' | 'bundle' | 'cardinal' | 'cardinal-open' | 'cardinal-closed' | 'catmull-rom' | 'catmull-rom-open' | 'catmull-rom-closed' | 'linear' | 'linear-closed' | 'monotone-x' | 'monotone-y' | 'natural' | 'step' | 'step-after' | 'step-before'
